### ISSUE TITLE
饿了么签到

### ISSUE THREAD

**Issue by dongzi-L** [songyangzz/QxScripts#2]
饿了么新版软件更改了签到入口，变成了打卡领红包，不知道能不能修改下

**Comment by songyangzz** [comment]
> 饿了么新版软件更改了签到入口，变成了打卡领红包，不知道能不能修改下

我的新版没看到啊

**Comment by dongzi-L** [comment]
App store版本现在是9.0.10，是截图的这个页面吧，现在签到一直都是重复签到，签到失败的
![eleme](https://user-images.githubusercontent.com/62493180/83869926-ec839700-a75f-11ea-9598-2e73da97a853.JPG)

**Comment by songyangzz** [comment]
> App store版本现在是9.0.10，是截图的这个页面吧，现在签到一直都是重复签到，签到失败的
> 
> ![eleme](https://user-images.githubusercontent.com/62493180/83869926-ec839700-a75f-11ea-9598-2e73da97a853.JPG)
> 
> 

我就说这个版本.没有.估计地区不一样吧

**Comment by dongzi-L** [comment]
嗯嗯，还真是不太清楚怎么回事

**Comment by songyangzz** [comment]
> 嗯嗯，还真是不太清楚怎么回事

部分内测.等都改了再考虑

**Comment by dongzi-L** [comment]
嗯嗯，谢谢
